
services:
  app:
    image: javacf/house-jesus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - my-network-name
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "720M"
networks:
  my-network-name:
    name: springcloud
